// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_Join
	//	*ClientEvent_Leave
	//	*ClientEvent_Send
	//	*ClientEvent_Typing
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetJoin() *JoinRoom {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientEvent) GetLeave() *LeaveRoom {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

func (x *ClientEvent) GetSend() *SendMessage {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *ClientEvent) GetTyping() *Typing {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Join struct {
	Join *JoinRoom `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientEvent_Leave struct {
	Leave *LeaveRoom `protobuf:"bytes,2,opt,name=leave,proto3,oneof"`
}

type ClientEvent_Send struct {
	Send *SendMessage `protobuf:"bytes,3,opt,name=send,proto3,oneof"`
}

type ClientEvent_Typing struct {
	Typing *Typing `protobuf:"bytes,4,opt,name=typing,proto3,oneof"`
}

func (*ClientEvent_Join) isClientEvent_Event() {}

func (*ClientEvent_Leave) isClientEvent_Event() {}

func (*ClientEvent_Send) isClientEvent_Event() {}

func (*ClientEvent_Typing) isClientEvent_Event() {}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Message
	//	*ServerEvent_UserJoined
	//	*ServerEvent_UserLeft
	//	*ServerEvent_UserTyping
	//	*ServerEvent_Error
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetMessage() *ChatMessage {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ServerEvent) GetUserJoined() *UserJoined {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserJoined); ok {
			return x.UserJoined
		}
	}
	return nil
}

func (x *ServerEvent) GetUserLeft() *UserLeft {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserLeft); ok {
			return x.UserLeft
		}
	}
	return nil
}

func (x *ServerEvent) GetUserTyping() *UserTyping {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UserTyping); ok {
			return x.UserTyping
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Message struct {
	Message *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ServerEvent_UserJoined struct {
	UserJoined *UserJoined `protobuf:"bytes,2,opt,name=user_joined,json=userJoined,proto3,oneof"`
}

type ServerEvent_UserLeft struct {
	UserLeft *UserLeft `protobuf:"bytes,3,opt,name=user_left,json=userLeft,proto3,oneof"`
}

type ServerEvent_UserTyping struct {
	UserTyping *UserTyping `protobuf:"bytes,4,opt,name=user_typing,json=userTyping,proto3,oneof"`
}

type ServerEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ServerEvent_Message) isServerEvent_Event() {}

func (*ServerEvent_UserJoined) isServerEvent_Event() {}

func (*ServerEvent_UserLeft) isServerEvent_Event() {}

func (*ServerEvent_UserTyping) isServerEvent_Event() {}

func (*ServerEvent_Error) isServerEvent_Event() {}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoom) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *JoinRoom) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveRoom) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Typing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Typing) Reset() {
	*x = Typing{}
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Typing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Typing) ProtoMessage() {}

func (x *Typing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Typing.ProtoReflect.Descriptor instead.
func (*Typing) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *Typing) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UserJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoined) Reset() {
	*x = UserJoined{}
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoined) ProtoMessage() {}

func (x *UserJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoined.ProtoReflect.Descriptor instead.
func (*UserJoined) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UserJoined) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *UserJoined) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeft) Reset() {
	*x = UserLeft{}
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeft) ProtoMessage() {}

func (x *UserLeft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeft.ProtoReflect.Descriptor instead.
func (*UserLeft) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *UserLeft) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *UserLeft) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserTyping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTyping) Reset() {
	*x = UserTyping{}
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTyping) ProtoMessage() {}

func (x *UserTyping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTyping.ProtoReflect.Descriptor instead.
func (*UserTyping) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *UserTyping) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *UserTyping) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRoomResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsRequest) Reset() {
	*x = ListRoomsRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsRequest) ProtoMessage() {}

func (x *ListRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{13}
}

type ListRoomsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []string               `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomsResponse) Reset() {
	*x = ListRoomsResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomsResponse) ProtoMessage() {}

func (x *ListRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ListRoomsResponse) GetRooms() []string {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_chat_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{15}
}

func (x *GetMessagesRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_chat_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_chat_proto_rawDescGZIP(), []int{16}
}

func (x *GetMessagesResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_proto_chat_chat_proto protoreflect.FileDescriptor

const file_proto_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/chat/chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\vClientEvent\x12$\n" +
	"\x04join\x18\x01 \x01(\v2\x0e.chat.JoinRoomH\x00R\x04join\x12'\n" +
	"\x05leave\x18\x02 \x01(\v2\x0f.chat.LeaveRoomH\x00R\x05leave\x12'\n" +
	"\x04send\x18\x03 \x01(\v2\x11.chat.SendMessageH\x00R\x04send\x12&\n" +
	"\x06typing\x18\x04 \x01(\v2\f.chat.TypingH\x00R\x06typingB\a\n" +
	"\x05event\"\x88\x02\n" +
	"\vServerEvent\x12-\n" +
	"\amessage\x18\x01 \x01(\v2\x11.chat.ChatMessageH\x00R\amessage\x123\n" +
	"\vuser_joined\x18\x02 \x01(\v2\x10.chat.UserJoinedH\x00R\n" +
	"userJoined\x12-\n" +
	"\tuser_left\x18\x03 \x01(\v2\x0e.chat.UserLeftH\x00R\buserLeft\x123\n" +
	"\vuser_typing\x18\x04 \x01(\v2\x10.chat.UserTypingH\x00R\n" +
	"userTyping\x12(\n" +
	"\x05error\x18\x05 \x01(\v2\x10.chat.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\":\n" +
	"\bJoinRoom\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x1f\n" +
	"\tLeaveRoom\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\";\n" +
	"\vSendMessage\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x1c\n" +
	"\x06Typing\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\"\xa1\x01\n" +
	"\vChatMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"<\n" +
	"\n" +
	"UserJoined\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\":\n" +
	"\bUserLeft\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"<\n" +
	"\n" +
	"UserTyping\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12CreateRoomResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10ListRoomsRequest\")\n" +
	"\x11ListRoomsResponse\x12\x14\n" +
	"\x05rooms\x18\x01 \x03(\tR\x05rooms\">\n" +
	"\x12GetMessagesRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x13GetMessagesResponse\x12-\n" +
	"\bmessages\x18\x01 \x03(\v2\x11.chat.ChatMessageR\bmessages2\x84\x02\n" +
	"\vChatService\x122\n" +
	"\x06Stream\x12\x11.chat.ClientEvent\x1a\x11.chat.ServerEvent(\x010\x01\x12?\n" +
	"\n" +
	"CreateRoom\x12\x17.chat.CreateRoomRequest\x1a\x18.chat.CreateRoomResponse\x12<\n" +
	"\tListRooms\x12\x16.chat.ListRoomsRequest\x1a\x17.chat.ListRoomsResponse\x12B\n" +
	"\vGetMessages\x12\x18.chat.GetMessagesRequest\x1a\x19.chat.GetMessagesResponseB)Z'github.com/sinavaelii/NexMsg/proto/chatb\x06proto3"

var (
	file_proto_chat_chat_proto_rawDescOnce sync.Once
	file_proto_chat_chat_proto_rawDescData []byte
)

func file_proto_chat_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)))
	})
	return file_proto_chat_chat_proto_rawDescData
}

var file_proto_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_chat_chat_proto_goTypes = []any{
	(*ClientEvent)(nil),           // 0: chat.ClientEvent
	(*ServerEvent)(nil),           // 1: chat.ServerEvent
	(*JoinRoom)(nil),              // 2: chat.JoinRoom
	(*LeaveRoom)(nil),             // 3: chat.LeaveRoom
	(*SendMessage)(nil),           // 4: chat.SendMessage
	(*Typing)(nil),                // 5: chat.Typing
	(*ChatMessage)(nil),           // 6: chat.ChatMessage
	(*UserJoined)(nil),            // 7: chat.UserJoined
	(*UserLeft)(nil),              // 8: chat.UserLeft
	(*UserTyping)(nil),            // 9: chat.UserTyping
	(*ErrorEvent)(nil),            // 10: chat.ErrorEvent
	(*CreateRoomRequest)(nil),     // 11: chat.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 12: chat.CreateRoomResponse
	(*ListRoomsRequest)(nil),      // 13: chat.ListRoomsRequest
	(*ListRoomsResponse)(nil),     // 14: chat.ListRoomsResponse
	(*GetMessagesRequest)(nil),    // 15: chat.GetMessagesRequest
	(*GetMessagesResponse)(nil),   // 16: chat.GetMessagesResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_proto_chat_chat_proto_depIdxs = []int32{
	2,  // 0: chat.ClientEvent.join:type_name -> chat.JoinRoom
	3,  // 1: chat.ClientEvent.leave:type_name -> chat.LeaveRoom
	4,  // 2: chat.ClientEvent.send:type_name -> chat.SendMessage
	5,  // 3: chat.ClientEvent.typing:type_name -> chat.Typing
	6,  // 4: chat.ServerEvent.message:type_name -> chat.ChatMessage
	7,  // 5: chat.ServerEvent.user_joined:type_name -> chat.UserJoined
	8,  // 6: chat.ServerEvent.user_left:type_name -> chat.UserLeft
	9,  // 7: chat.ServerEvent.user_typing:type_name -> chat.UserTyping
	10, // 8: chat.ServerEvent.error:type_name -> chat.ErrorEvent
	17, // 9: chat.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 10: chat.GetMessagesResponse.messages:type_name -> chat.ChatMessage
	0,  // 11: chat.ChatService.Stream:input_type -> chat.ClientEvent
	11, // 12: chat.ChatService.CreateRoom:input_type -> chat.CreateRoomRequest
	13, // 13: chat.ChatService.ListRooms:input_type -> chat.ListRoomsRequest
	15, // 14: chat.ChatService.GetMessages:input_type -> chat.GetMessagesRequest
	1,  // 15: chat.ChatService.Stream:output_type -> chat.ServerEvent
	12, // 16: chat.ChatService.CreateRoom:output_type -> chat.CreateRoomResponse
	14, // 17: chat.ChatService.ListRooms:output_type -> chat.ListRoomsResponse
	16, // 18: chat.ChatService.GetMessages:output_type -> chat.GetMessagesResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_chat_chat_proto_init() }
func file_proto_chat_chat_proto_init() {
	if File_proto_chat_chat_proto != nil {
		return
	}
	file_proto_chat_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_Join)(nil),
		(*ClientEvent_Leave)(nil),
		(*ClientEvent_Send)(nil),
		(*ClientEvent_Typing)(nil),
	}
	file_proto_chat_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerEvent_Message)(nil),
		(*ServerEvent_UserJoined)(nil),
		(*ServerEvent_UserLeft)(nil),
		(*ServerEvent_UserTyping)(nil),
		(*ServerEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_chat_proto_rawDesc), len(file_proto_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_chat_proto_depIdxs,
		MessageInfos:      file_proto_chat_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_chat_proto = out.File
	file_proto_chat_chat_proto_goTypes = nil
	file_proto_chat_chat_proto_depIdxs = nil
}
